openapi: '3.0.2'
info:
  title: Simple API example for OpenAPI Validation
  version: '1.0'
servers:
  - url: http://localhost:2000
paths:
  /customers:
    parameters:
      - in: query
        name: limit
        required: false
        schema:
          type: integer
          maximum: 100
          minimum: 0
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  persons:
                    type: array
                    items:
                      $ref: "#/components/schemas/Customer"
    post:
       requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Customer"
       responses:
        '200':
          description: OK     

components:
  schemas:
    Customer:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          maxLength: 10