openapi: '3.0.2'
info:
  title: Person API to demo OpenAPI Validation
  version: '1.0'
servers:
  - url: http://localhost:3000/
paths:
  /persons:
    post:
       requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Person"
       responses:
        '200':
          description: OK     

components:
  schemas:
    Person:
      type: object
      additionalProperties: false
      required: ["name"]
      properties:
        name:
          type: string
          minLength: 3
        email:
          type: string
          format: email
        age:
          type: integer
          minimum: 0
        
