openapi: '3.0.2'
info:
  title: Fruit Shop API
  version: '1.0'
  x-membrane-id: fruitshop
servers:
  - url: https://api.predic8.de/shop
paths:
  /products/:
    get:
      tags:
        - Shop
      parameters:
        - name: limit
          in: query
          required: false
          schema: 
            type: integer
            maximum: 100
            minimum: 0
            example: 10
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductList"
    post:
      tags:
        - Shop
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"

      responses:
        '200':
          description: OK
  /products/{pid}:
    parameters:
      - in: path
        name: pid
        schema:
          type: integer
          minimum: 0
        required: true
    get:
      tags:
        - Shop
      responses:
        '200':
          description: OK      

components:
  schemas:
    ProductList:
      type: object
      properties:
        meta:
          type: object
        products:
          type: object
          properties:
            name:
              type: string
            product_url:
              type: string
    Product:
      type: object
      required: ["name","price"]
      additionalProperties: false
      properties:
        name:
          type: string
          example: Figs
          maxLength: 10
        price:
          type: number
          example: 2.70
          minimum: 0
        category_url:
          type: string
          example: /shop/categories/Fruits
        vendor_url:
          type: string
          example: /shop/vendors/672



