openapi: '3.0.2'
info:
  title: Person API to demo OpenAPI Validation
  version: '1.0'
servers:
  - url: http://localhost:3000/demo-api/v2/
paths:
  /persons:
    parameters:
      - in: query
        name: limit
        required: false
        schema:
          type: integer
          maximum: 100
          minimum: 0
    get:
      responses:
        201:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  persons:
                    type: array
                    items:
                      $ref: "#/components/schemas/Person"
  /persons/{pid}:
    parameters:
      - in: path
        name: pid
        required: true
        schema: 
          type: string
          format: uuid
    put:
       requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Person"
       responses:
        '200':
          description: OK     

components:
  schemas:
    Person:
      type: object
      additionalProperties: false
      required: ["id","name"]
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          minLength: 3
          maxLength: 12
        email:
          type: string
          format: email
        type:
          type: string
          enum: ['PRIVAT','BUSINESS']
        
